add swagger doc update as pre commit hook

diff --git a/cloud-builders/go-common/etc/pre-commit b/cloud-builders/go-common/etc/pre-commit
--- a/cloud-builders/go-common/etc/pre-commit
+++ b/cloud-builders/go-common/etc/pre-commit
@@ -1,5 +1,13 @@
 #!/bin/sh
 
+./make.sh swag-doc
+if [ $? = 0 ]; then
+  echo 'swagger updated ✅'
+else
+  echo 'swagger failed ❌'
+  exit 1
+fi
+
 ./make.sh lint
 if [ $? = 0 ]; then
   echo 'lint passed ✅'
